services:
  # A Docker web service
  - type: web
    name: disease_prediction
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn Backend.app.main:app --host 0.0.0.0 --port $PORT